/*
   XOR BASIS (Linear Basis over GF(2))
   
   Idea:
   - Represents a set of numbers using a minimal set of linearly independent 
     numbers (basis).
   - Any XOR sum of a subset in the original set can be formed by a XOR sum 
     of a subset of the basis.
   - The size of the basis never exceeds the number of bits (LOG_D).
   
   Complexity:
   - Insert / Check / Get Max: O(LOG_D)
   - Merge two bases: O(LOG_D^2)
   - Build RREF: O(LOG_D^2)
   - K-th Smallest/Largest: O(LOG_D)
*/

#include <bits/stdc++.h>
using namespace std;

const int LOG_D = 60; // 60 for values up to 10^18, 30 for values up to 10^9

struct XorBasis {
  long long basis[LOG_D];
  int sz; // Number of elements currently in the basis
  vector<long long> reduced_basis; // Stores the canonical form for K-th queries

  XorBasis() {
    memset(basis, 0, sizeof(basis));
    sz = 0;
  }

  // 1. Insert a value. Returns true if successfully inserted 
  // (i.e., the value is linearly independent from the current basis).
  bool insert(long long x) {
    for (int i = LOG_D - 1; i >= 0; i--) {
      if ((x >> i) & 1) {
        if (!basis[i]) {
          basis[i] = x;
          sz++;
          return true;
        }
        x ^= basis[i];
      }
    }
    return false; // x became 0, meaning it was already spanned by the basis
  }

  // 2. Check if a value can be formed by XORing a subset of the basis
  bool check(long long x) {
    for (int i = LOG_D - 1; i >= 0; i--) {
      if ((x >> i) & 1) {
        if (!basis[i]) return false;
        x ^= basis[i];
      }
    }
    return true; 
  }

  // 3. Get the maximum possible XOR sum using the basis.
  long long get_max(long long start_val = 0) {
    long long res = start_val;
    for (int i = LOG_D - 1; i >= 0; i--) {
      if ((res ^ basis[i]) > res) {
        res ^= basis[i];
      }
    }
    return res;
  }

  // 4. Merge this basis with another basis
  void merge(const XorBasis& other) {
    for (int i = 0; i < LOG_D; i++) {
      if (other.basis[i]) {
        insert(other.basis[i]);
      }
    }
  }

  // -----------------------------------------------------------------------
  // K-TH LARGEST / SMALLEST QUERIES
  // Note: These functions only consider DISTINCT values generated by the basis.
  // There are exactly 2^sz distinct values (including 0 from the empty subset).
  // -----------------------------------------------------------------------

  // 5. Build Reduced Row Echelon Form (Canonical Form)
  // MUST be called after all inserts and BEFORE querying k-th values!
  void build() {
    reduced_basis.clear();
    for (int i = LOG_D - 1; i >= 0; i--) {
      for (int j = i - 1; j >= 0; j--) {
        // If the j-th bit of basis[i] is set, use basis[j] to turn it off
        if ((basis[i] >> j) & 1) {
          basis[i] ^= basis[j];
        }
      }
    }
    // Collect non-zero elements into the reduced_basis array (in ascending order)
    for (int i = 0; i < LOG_D; i++) {
      if (basis[i]) {
        reduced_basis.push_back(basis[i]);
      }
    }
  }

  // 6. Get the k-th smallest distinct XOR sum (1-indexed).
  // k = 1 returns 0 (the empty subset).
  // Returns -1 if k is out of bounds (k > 2^sz).
  long long get_kth_smallest(long long k) {
    long long total_combinations = 1LL << sz;
    if (k < 1 || k > total_combinations) return -1;
    
    long long rank = k - 1; // 0-indexed rank
    long long res = 0;
    for (int i = 0; i < sz; i++) {
      if ((rank >> i) & 1) {
        res ^= reduced_basis[i];
      }
    }
    return res;
  }

  // 7. Get the k-th largest distinct XOR sum (1-indexed).
  // k = 1 returns the absolute maximum possible XOR sum.
  // Returns -1 if k is out of bounds (k > 2^sz).
  long long get_kth_largest(long long k) {
    long long total_combinations = 1LL << sz;
    if (k < 1 || k > total_combinations) return -1;
    
    // The k-th largest is equivalent to the (total_combinations - k)-th smallest
    long long rank = total_combinations - k; 
    long long res = 0;
    for (int i = 0; i < sz; i++) {
      if ((rank >> i) & 1) {
        res ^= reduced_basis[i];
      }
    }
    return res;
  }
};

/*
   USAGE EXAMPLE:
   
   signed main() {
     int n = 3;
     long long a[] = {2, 4, 6}; // 2 (010), 4 (100), 6 (110)
     
     XorBasis xb;
     for (int i = 0; i < n; i++) xb.insert(a[i]);
     
     // 1. Build the canonical form before calling k-th queries
     xb.build();
     
     // The distinct XOR sums generated are: 0, 2, 4, 6
     // Since 6 is just 2 ^ 4, the basis size (sz) will be 2. (2^2 = 4 combinations)
     
     cout << "Max XOR sum: " << xb.get_max() << "\n"; // 6
     
     cout << "1st smallest: " << xb.get_kth_smallest(1) << "\n"; // 0
     cout << "2nd smallest: " << xb.get_kth_smallest(2) << "\n"; // 2
     
     cout << "1st largest: " << xb.get_kth_largest(1) << "\n"; // 6
     cout << "3rd largest: " << xb.get_kth_largest(3) << "\n"; // 2
     
     return 0;
   }
*/